// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"
)

type Url struct {
	ID        int32
	Url       string
	Code      string
	CreatedAt time.Time
}
