// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Tag struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}

type Url struct {
	ID        int32
	Url       string
	Code      string
	ExpiresAt pgtype.Timestamptz
	UpdatedAt time.Time
	CreatedAt time.Time
}

type UrlTag struct {
	ID        int32
	UrlID     int32
	TagID     int32
	CreatedAt time.Time
}
