// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AddTagToURL(ctx context.Context, arg AddTagToURLParams) error
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteTag(ctx context.Context, id int32) error
	DeleteURL(ctx context.Context, id int32) error
	GetTags(ctx context.Context) ([]Tag, error)
	GetTagsForURL(ctx context.Context, urlID int32) ([]Tag, error)
	GetURLByCode(ctx context.Context, code string) (Url, error)
	GetURLByID(ctx context.Context, id int32) (Url, error)
	GetURLsWithTags(ctx context.Context) ([]GetURLsWithTagsRow, error)
	GetVisits(ctx context.Context) ([]Visit, error)
	GetVisitsForURL(ctx context.Context, urlID int32) ([]Visit, error)
	RemoveTagFromURL(ctx context.Context, arg RemoveTagFromURLParams) error
}

var _ Querier = (*Queries)(nil)
