// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repo

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (url, code)
VALUES ($1, $2)
RETURNING id, url, code, created_at
`

type CreateUrlParams struct {
	Url  string `json:"url"`
	Code string `json:"code"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.Url, arg.Code)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const findUrlByCode = `-- name: FindUrlByCode :one
SELECT id, url, code, created_at 
FROM urls 
WHERE code = $1
`

func (q *Queries) FindUrlByCode(ctx context.Context, code string) (Url, error) {
	row := q.db.QueryRow(ctx, findUrlByCode, code)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}
